#!/bin/bash
clr="$RED_COLOR"
____paused() {
	printf "^c$BLUE_COLOR^ ^c$WHITE_COLOR^"
}

____mpc() {
	clr="$ORANGE_COLOR"
	printf "^c$clr^  ^c$LIGHT_BLUE_COLOR^%s -^c$GREEN_COLOR^ %s^c$WHITE_COLOR^" "$(mpc current -f %artist%)" "$(mpc current -f %title%)"
	printf "^c$clr^  ^c$LIGHT_BLUE_COLOR^%s -^c$GREEN_COLOR^ %s^c$WHITE_COLOR^" "$(mpc current -f %artist%)" "$(mpc current -f %title%)" >"$__CFILE_"
}

[[ "$(mpc status | sed -n 2p | awk '{print $1;}')" == "[playing]" ]] && ____mpc || ____paused
