#!/bin/sh

# Exit if no battery exists
if [ ! -f /sys/class/power_supply/BAT0/capacity ]; then
	printf "^c%s^ " "$BLUE_COLOR"
	exit 0
fi

battery_percentage=$(cat /sys/class/power_supply/BAT0/capacity)
charging=$(acpi 2>/dev/null | awk '{print $3}')
NFILE="$HOME/scripts/nfile"
min_battery_allowed=20

# Low battery notification
if [ "$battery_percentage" -lt "$min_battery_allowed" ] && [ ! -e "$NFILE" ]; then
	touch "$NFILE"
	notify-send -u critical "Low Battery!" "Please Plugin The Charge"
fi

# Remove notification file when battery is sufficient
if [ "$battery_percentage" -ge "$min_battery_allowed" ] && [ -e "$NFILE" ]; then
	rm "$NFILE"
fi

if [ "$charging" = "Charging," ]; then
	printf " ^c%s^  %s  " "$YELLOW_COLOR" "$battery_percentage"
else
	printf " ^c%s^  %s " "$YELLOW_COLOR" "$battery_percentage"
fi
