[colors]
draw_bold_text_with_bright_colors = false

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR="1.0"

[font]
size = 13

[font.normal]
family = "Ubuntu Sans Mono"
style = "Regular"

[font.bold]
family = "Ubuntu Sans Mono"
style = "Regular"

[window]
opacity = 1
dynamic_title = false
