[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = "#181818"
foreground = "#E4E4E4"

[colors.normal]
black   = "#181818"
red     = "#F43841"
green   = "#73D936"
yellow  = "#FFDD33"
blue    = "#96A6C8"
magenta = "#9E95C7"
cyan    = "#95A99F"
white   = "#E4E4E4"

[colors.bright]
black   = "#52494E"
red     = "#FF4F58"
green   = "#73D936"
yellow  = "#FFDD33"
blue    = "#96A6C8"
magenta = "#AFAFD7"
cyan    = "#95A99F"
white   = "#F5F5F5"

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "Ubuntu Sans Mono"
style = "Regular"

[font.bold]
family = "Ubuntu Sans Mono"
style = "Regular"

[window]
opacity = 1
dynamic_title = false
